flow fix
Signed-off-by: sanjin94 <sanjin.gumbarevic@gmail.com>

diff --git a/.github/workflows/delivery_flow.yaml b/.github/workflows/delivery_flow.yaml
--- a/.github/workflows/delivery_flow.yaml
+++ b/.github/workflows/delivery_flow.yaml
@@ -24,14 +24,14 @@ jobs:
         uses: actions/checkout@v2
       #TODO build image
       #TODO push to hub
-      - name: Test telegram
-        run: exit 1
-      - name: Notify Telegram on failure
-        if: failure()
-        uses: sanjin94/HFMpred/.github/actions/telegram_warning@811cfacce37b231c7c4cd45213ed7271f28406dc
-        with:
-          telegram-bot-token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
-          telegram-chat-id: ${{ secrets.TELEGRAM_CHAT_ID }}
+      #- name: Test telegram
+      #  run: exit 1
+      #- name: Notify Telegram on failure
+      #  if: failure()
+      #  uses: sanjin94/HFMpred/.github/actions/telegram_warning@master
+      #  with:
+      #    telegram-bot-token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
+      #    telegram-chat-id: ${{ secrets.TELEGRAM_CHAT_ID }}
   test:
     runs-on: ubuntu-latest
     steps:
@@ -46,18 +46,18 @@ jobs:
           python --version
           python -m pip install --upgrade pip
           pip install -r requirements.txt
-      - name: Lint code
-        uses: sanjin94/HFMpred/.github/actions/static_test@811cfacce37b231c7c4cd45213ed7271f28406dc
-        with:
-          pylint-options: ${{ inputs.pylint-options }}
+      #- name: Lint code
+      #  uses: sanjin94/HFMpred/.github/actions/static_test@master
+      #  with:
+      #    pylint-options: ${{ inputs.pylint-options }}
       #TODO
       #- name: Test code
       #  run: pytest tests/
-      - name: Test telegram
-        run: exit 1
-      - name: Notify Telegram on failure
-        if: failure()
-        uses: sanjin94/HFMpred/.github/actions/telegram_warning@811cfacce37b231c7c4cd45213ed7271f28406dc
-        with:
-          telegram-bot-token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
-          telegram-chat-id: ${{ secrets.TELEGRAM_CHAT_ID }}
+      #- name: Test telegram
+      #  run: exit 1
+      #- name: Notify Telegram on failure
+      #  if: failure()
+      #  uses: sanjin94/HFMpred/.github/actions/telegram_warning@master
+      #  with:
+      #    telegram-bot-token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
+      #    telegram-chat-id: ${{ secrets.TELEGRAM_CHAT_ID }}
